import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { signIn } from 'next-auth/react'
import { NextPageWithLayout } from './_app'
import { useEffect } from 'react'

const SignIn: NextPageWithLayout = () => {
  let button = (
    <button className='btn btn-primary' onClick={() => signIn('okta', { redirect: true, callbackUrl: '/' })}>
      Login
    </button>
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1>Please Sign In</h1>
        {button}
      </main>
    </div>
  )
}

SignIn.requireAuth = false

export default SignIn
